language: php
install: 
  - wget -O test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./test-reporter
  - ./test-reporter before-build
  - composer install -o --dev
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
after_success:
  - CODECLIMATE_REPO_TOKEN=f395264854ad7aa9a1026bcaf3fe7b2961c75ac66007fe1ddb2cbb39049a7385 ./vendor/bin/test-reporter after-build
